# COMMON APPLICATION PROPERTIES

# start services on random port by default
server.port: 0

# database init, supports mysql too
petclinic.database: hsqldb
spring:
  datasource:
    schema: classpath*:db/${petclinic.database}/schema.sql
    data: classpath*:db/${petclinic.database}/data.sql
  sleuth:
    sampler:
      percentage: 1.0

# JPA
spring.jpa.hibernate.ddl-auto: none

# Logging
logging.level.org.springframework: INFO

---
spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_HOST}:${EUREKA_PORT}/eureka/
      
  instance:
    hostname: ${HOST_NAME}
